using System.ComponentModel.DataAnnotations;

namespace ProductCrudApp.Api.Models;

// The "Model" in MVC: the EF Core entity mapped directly to the "Products" table
// in SQL Server. Data annotations double as EF Core column constraints and
// ASP.NET Core model-validation rules.
public class Product
{
    // Primary key, auto-generated by SQL Server (IDENTITY column).
    public int Id { get; set; }

    [Required]
    [MaxLength(200)]
    public string Name { get; set; } = string.Empty;

    [MaxLength(1000)]
    public string? Description { get; set; }

    [Range(0, double.MaxValue)]
    public decimal Price { get; set; }

    [Range(0, int.MaxValue)]
    public int StockQuantity { get; set; }

    // Set once at creation time; not updated afterwards.
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
}
